### ISSUE TITLE
sam-minikube.yaml Needs Updates for k8s v1.16

### ISSUE THREAD

**Issue by danchirillo** [jonpharry/labfiles#1]
**Environment**
macOS 10.14.6
minikube version: v1.4.0
kubectl version:  1.16.0

I ran into 2 issues with `sam-minikube.yaml` going through SAM906-Kubernetes 20190509.pdf and running `kubectl create -f`:

1.  `Deployment`'s  `apiVersion` is now `apps/v1`
2.  `Deployment.spec` now requires a `selector`.  I followed this pattern for all the deployments:
```
spec:
  selector:
    matchLabels:
      app: <openldap>
```
